Connected to Python 3.12.1

In [ ]:
# load our libraries setup up our environment for data analysis and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression # (pip install scikit-learn)
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

 ## We are going to work through the Data Science Lifecyle exploring each step
 ### Step 1 Define a question...we can also start with the data but today we are doing the question first

 #### **Question: Which feature(s) of a vehicle most contributes to lower Miles Per Gallon?**
 We are going to use a dataset inside of the seaborn package called "mpg"

 #### **Question: Which feature(s) of a vehicle most contributes to lower Miles Per Gallon?**
 We are going to use a dataset inside of the seaborn package called "mpg"

In [ ]:
df = sns.load_dataset("mpg")

In [ ]:
print(df.head()) # shows the first 5 rows of the dataframe
 # shows a summary of the dataframe including data types and non-null counts

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [ ]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [ ]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [ ]:
print(df.info()) # What do we notice here?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

In [ ]:
print(df.info()) # What do we notice here?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

In [ ]:
print(df.head()) # shows the first 5 rows of the dataframe
 # shows a summary of the dataframe including data types and non-null counts

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [ ]:
print(df.info()) # What do we notice here?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

In [ ]:
df = sns.load_dataset("mpg")

In [ ]:
print(df.head()) # shows the first 5 rows of the dataframe
 # shows a summary of the dataframe including data types and non-null counts

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [ ]:
print(df.info()) # What do we notice here?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

In [ ]:
# load our libraries setup up our environment for data analysis and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression # (pip install scikit-learn)
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

 ## We are going to work through the Data Science Lifecyle exploring each step
 ### Step 1 Define a question...we can also start with the data but today we are doing the question first

 #### **Question: Which feature(s) of a vehicle most contributes to lower Miles Per Gallon?**
 We are going to use a dataset inside of the seaborn package called "mpg"

In [ ]:
df = sns.load_dataset("mpg")

In [ ]:
print(df.head()) # shows the first 5 rows of the dataframe
 # shows a summary of the dataframe including data types and non-null counts

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0
3  16.0          8         304.0       150.0    3433          12.0
4  17.0          8         302.0       140.0    3449          10.5

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite
3          70    usa              amc rebel sst
4          70    usa                ford torino

In [ ]:
print(df.info()) # What do we notice here?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

Connected to Python 3.12.1

In [ ]:
df.describe()

NameError: name 'df' is not defined

 #### Common Python Data Types

 - **int**: Integer type, used to represent whole numbers.
     *Example*: `x = 5`

 - **float**: Floating point type, used for real numbers (decimals).
     *Example*: `y = 3.14`

 - **str**: String type, used for text data.
     *Example*: `name = "Alice"`

 - **bool**: Boolean type, represents `True` or `False` values.
     *Example*: `is_valid = True`

 - **list**: Ordered, mutable collection of items.
     *Example*: `numbers = [1, 2, 3]`

 - **tuple**: Ordered, immutable collection of items.
     *Example*: `point = (10, 20)`

 - **dict**: Dictionary type, stores key-value pairs.
     *Example*: `person = {"name": "Bob", "age": 30}`

 - **set**: Unordered collection of unique items.
     *Example*: `unique_numbers = {1, 2, 3}`

 - **NoneType**: Represents the absence of a value.
     *Example*: `result = None`

 #### Common Python Data Types

 - **int**: Integer type, used to represent whole numbers.
     *Example*: `x = 5`

 - **float**: Floating point type, used for real numbers (decimals).
     *Example*: `y = 3.14`

 - **str**: String type, used for text data.
     *Example*: `name = "Alice"`

 - **bool**: Boolean type, represents `True` or `False` values.
     *Example*: `is_valid = True`

 - **list**: Ordered, mutable collection of items.
     *Example*: `numbers = [1, 2, 3]`

 - **tuple**: Ordered, immutable collection of items.
     *Example*: `point = (10, 20)`

 - **dict**: Dictionary type, stores key-value pairs.
     *Example*: `person = {"name": "Bob", "age": 30}`

 - **set**: Unordered collection of unique items.
     *Example*: `unique_numbers = {1, 2, 3}`

 - **NoneType**: Represents the absence of a value.
     *Example*: `result = None`

 #### Common Python Data Types

 - **int**: Integer type, used to represent whole numbers.
     *Example*: `x = 5`

 - **float**: Floating point type, used for real numbers (decimals).
     *Example*: `y = 3.14`

 - **str**: String type, used for text data.
     *Example*: `name = "Alice"`

 - **bool**: Boolean type, represents `True` or `False` values.
     *Example*: `is_valid = True`

 - **list**: Ordered, mutable collection of items.
     *Example*: `numbers = [1, 2, 3]`

 - **tuple**: Ordered, immutable collection of items.
     *Example*: `point = (10, 20)`

 - **dict**: Dictionary type, stores key-value pairs.
     *Example*: `person = {"name": "Bob", "age": 30}`

 - **set**: Unordered collection of unique items.
     *Example*: `unique_numbers = {1, 2, 3}`

 - **NoneType**: Represents the absence of a value.
     *Example*: `result = None`

In [ ]:
print(df.dtypes) # check for the data types of each column

NameError: name 'df' is not defined

 #### Common Pandas Data Types

 - **int64**: Integer values (whole numbers).
     *Example*: `1, 42, -7`

 - **float64**: Floating point numbers (decimals).
     *Example*: `3.14, -0.001, 100.0`

 - **object**: Typically used for text or mixed types (strings, categorical data, or Python objects).
     *Example*: `"sedan", "usa", "ford mustang"`

 - **bool**: Boolean values (`True` or `False`).
     *Example*: `True, False`

 - **datetime64[ns]**: Date and time values with nanosecond precision.
     *Example*: `2024-06-01 12:00:00`

 - **category**: Categorical data for efficient storage of repeated string values.
     *Example*: `["low", "medium", "high"]` as categories

 - **timedelta[ns]**: Differences between two datetime values (time durations).
     *Example*: `2 days, 5 hours`

 These data types help pandas optimize storage and operations on your data.

 #### Common Pandas Data Types

 - **int64**: Integer values (whole numbers).
     *Example*: `1, 42, -7`

 - **float64**: Floating point numbers (decimals).
     *Example*: `3.14, -0.001, 100.0`

 - **object**: Typically used for text or mixed types (strings, categorical data, or Python objects).
     *Example*: `"sedan", "usa", "ford mustang"`

 - **bool**: Boolean values (`True` or `False`).
     *Example*: `True, False`

 - **datetime64[ns]**: Date and time values with nanosecond precision.
     *Example*: `2024-06-01 12:00:00`

 - **category**: Categorical data for efficient storage of repeated string values.
     *Example*: `["low", "medium", "high"]` as categories

 - **timedelta[ns]**: Differences between two datetime values (time durations).
     *Example*: `2 days, 5 hours`

 These data types help pandas optimize storage and operations on your data.

 ### What data type is Cylinders?

 ### What data type is Cylinders?

In [ ]:
sns.kdeplot(df['cylinders'], fill=True)
plt.title('Density Plot of Cylinders')
plt.xlabel('Cylinders')
plt.ylabel('Density')
plt.show()

NameError: name 'sns' is not defined

In [ ]:
sns.countplot(x='cylinders', data=df)
plt.title('Count of Cars by Number of Cylinders')
plt.xlabel('Cylinders')
plt.ylabel('Count')
plt.show()

NameError: name 'sns' is not defined

In [ ]:
print(df.dtypes) # Are there other features that might need to be changed?

NameError: name 'df' is not defined